import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { Separator } from "@/components/ui/separator";
import { ScrollArea } from "@/components/ui/scroll-area";
import { 
  BookOpen,
  Plug,
  Code2,
  Sparkles,
  FileCode2,
  Terminal,
  MessageSquare,
  Download,
  ExternalLink
} from "lucide-react";
import { SiDiscord } from "react-icons/si";

const sections = [
  {
    id: "getting-started",
    title: "Getting Started",
    icon: BookOpen,
    content: `
## Welcome to Hideout Bot

Hideout Bot is an AI-powered game builder that helps you create Roblox games faster than ever. 
Simply describe what you want to build, and our AI will generate the Lua code for you.

### Quick Start

1. **Install the Plugin**: Download the Hideout Bot plugin from the Roblox Creator Store
2. **Connect Your Account**: Copy your User ID from the dashboard and paste it in the plugin
3. **Create a Project**: Start a new project from the dashboard
4. **Start Building**: Use natural language prompts to generate game code
    `
  },
  {
    id: "plugin-setup",
    title: "Plugin Setup",
    icon: Plug,
    content: `
## Installing the Plugin

### Step 1: Download
Download the Hideout Bot plugin from the official Roblox Creator Store.

### Step 2: Install
The plugin will appear in your Plugins tab in Roblox Studio.

### Step 3: Connect
1. Open Hideout Bot in Studio
2. Go to your Dashboard on hide-bot.com
3. Copy your User ID from the sidebar
4. Paste it into the plugin's User ID field
5. Click "Connect"

### Step 4: Select Project
Enter a Project ID to work on a specific project, or leave blank to work without a project.
    `
  },
  {
    id: "ai-prompts",
    title: "Writing AI Prompts",
    icon: MessageSquare,
    content: `
## Effective Prompting

The AI understands natural language, but following these tips will give you better results:

### Be Specific
Instead of "make a game", try "Create a 10-stage obby with checkpoints, kill bricks, and a stage leaderstat"

### Include Details
- Mention specific numbers (10 stages, 5 enemies, 3 weapons)
- Describe behavior (when touched, on click, every 5 seconds)
- Specify locations (in workspace, in ReplicatedStorage)

### Use Keywords
Asset keywords like "tree", "rock", "car" will automatically include those assets.

### Example Prompts

**Obby:**
"Create a checkpoint system where touching a checkpoint part saves the player's stage and respawns them there when they die"

**Tycoon:**
"Create a dropper that spawns cash parts every 2 seconds that give $10 when collected"

**Custom:**
"Create a tool giver GUI with buttons for Sword, Bow, and Shield that gives the corresponding tool when clicked"
    `
  },
  {
    id: "system-templates",
    title: "System Templates",
    icon: FileCode2,
    content: `
## Pre-built Game Systems

Hideout Bot includes ready-to-use templates for common game systems:

### Obby Systems
- **Checkpoints**: Save and load player progress
- **Kill Bricks**: Reset players to last checkpoint
- **Stage Leaderstats**: Track current stage
- **Speed Boosts**: Temporary speed increase

### Racing Systems
- **Lap Counter**: Track completed laps
- **Best Time**: Store fastest race time
- **Vehicle Spawner**: Give players vehicles
- **Race Manager**: Start/stop races

### Tycoon Systems
- **Currency**: Cash leaderstats
- **Droppers**: Generate collectibles
- **Collectors**: Collect and convert items
- **Upgrades**: Purchase improvements

### Universal Systems
- **DataStore**: Save/load player data
- **Tool Giver**: Grant tools on interaction
- **Teleporter**: Move players between areas
- **VIP Door**: Access control
    `
  },
  {
    id: "lua-code",
    title: "Understanding the Code",
    icon: Code2,
    content: `
## Generated Lua Code

All code generated by Hideout Bot is:

### Production-Ready
- Follows Roblox best practices
- Properly handles errors
- Uses efficient patterns

### Well-Organized
- Clear variable names
- Logical structure
- Easy to modify

### Copy-Paste Ready
1. Generate code in the dashboard
2. Copy from the output panel
3. Paste into the appropriate location in Studio

### Code Locations
- **ServerScriptService**: Server-side logic
- **StarterPlayerScripts**: Client-side logic
- **ReplicatedStorage**: Shared modules
- **StarterGui**: User interface
- **Workspace**: Physical objects
    `
  },
  {
    id: "support",
    title: "Support & Community",
    icon: SiDiscord,
    content: `
## Get Help

### Discord Community
Join our Discord server for:
- Live support from the community
- Share your creations
- Get tips and tricks
- Report bugs

**Discord**: discord.gg/rZbtJJ8XYV

### Reporting Issues
If you encounter bugs or have suggestions:
1. Check the Discord for known issues
2. Describe the problem in detail
3. Include any error messages
4. Share your prompt if relevant

### Feature Requests
We're always looking to improve! Share your ideas on Discord.
    `
  }
];

export default function Docs() {
  return (
    <div className="space-y-6">
      {/* Header */}
      <div>
        <h1 className="text-3xl font-bold" data-testid="text-docs-title">Documentation</h1>
        <p className="text-muted-foreground">
          Learn how to use Hideout Bot to build amazing Roblox games
        </p>
      </div>

      <div className="grid lg:grid-cols-4 gap-6">
        {/* Navigation */}
        <div className="lg:col-span-1">
          <Card className="sticky top-6">
            <CardHeader className="pb-3">
              <CardTitle className="text-base">Contents</CardTitle>
            </CardHeader>
            <CardContent className="space-y-1">
              {sections.map((section) => (
                <a
                  key={section.id}
                  href={`#${section.id}`}
                  className="flex items-center gap-2 px-3 py-2 rounded-md text-sm hover:bg-muted transition-colors"
                  data-testid={`link-section-${section.id}`}
                >
                  <section.icon className="w-4 h-4 text-muted-foreground" />
                  {section.title}
                </a>
              ))}
            </CardContent>
          </Card>
        </div>

        {/* Content */}
        <div className="lg:col-span-3 space-y-8">
          {sections.map((section) => (
            <Card key={section.id} id={section.id} data-testid={`section-${section.id}`}>
              <CardHeader>
                <CardTitle className="flex items-center gap-2">
                  <section.icon className="w-5 h-5 text-primary" />
                  {section.title}
                </CardTitle>
              </CardHeader>
              <CardContent>
                <div className="prose prose-sm dark:prose-invert max-w-none">
                  {section.content.split('\n').map((line, index) => {
                    if (line.startsWith('## ')) {
                      return <h2 key={index} className="text-xl font-bold mt-0 mb-4">{line.replace('## ', '')}</h2>;
                    }
                    if (line.startsWith('### ')) {
                      return <h3 key={index} className="text-lg font-semibold mt-6 mb-2">{line.replace('### ', '')}</h3>;
                    }
                    if (line.startsWith('**') && line.endsWith('**')) {
                      return <p key={index} className="font-semibold mt-4 mb-1">{line.replace(/\*\*/g, '')}</p>;
                    }
                    if (line.startsWith('- ')) {
                      return <li key={index} className="ml-4">{line.replace('- ', '')}</li>;
                    }
                    if (line.match(/^\d+\./)) {
                      return <li key={index} className="ml-4 list-decimal">{line.replace(/^\d+\.\s/, '')}</li>;
                    }
                    if (line.trim() === '') {
                      return null;
                    }
                    return <p key={index} className="text-muted-foreground">{line}</p>;
                  })}
                </div>
              </CardContent>
            </Card>
          ))}

          {/* Support CTA */}
          <Card className="border-primary/20">
            <CardContent className="py-8 text-center">
              <div className="w-16 h-16 rounded-2xl bg-primary/10 mx-auto mb-4 flex items-center justify-center">
                <SiDiscord className="w-8 h-8 text-primary" />
              </div>
              <h3 className="text-xl font-bold mb-2">Need More Help?</h3>
              <p className="text-muted-foreground mb-4">
                Join our Discord community for live support and updates
              </p>
              <a href="https://discord.gg/rZbtJJ8XYV" target="_blank" rel="noopener noreferrer">
                <Badge className="cursor-pointer text-base py-2 px-4">
                  <SiDiscord className="w-4 h-4 mr-2" />
                  Join Discord
                  <ExternalLink className="w-3 h-3 ml-2" />
                </Badge>
              </a>
            </CardContent>
          </Card>
        </div>
      </div>
    </div>
  );
}
